objetivo 0 - pull 1
pedromarting3/OnTime pull request #1
Opened 2022-09-20 09:54 UTC by pedromarting3

2022-09-20 10:48 UTC, JJ commented
La lista de comprobación está para que la pongáis. Si no la ponéis y os habéis saltado alguno de los pasos, es muy posible que lo que propongáis no sea correcto.

2022-09-20 10:50 UTC, JJ requested changes
No mencionas ni la lógica de negocio ni quienes son los clientes. El problema no está tan bien definido, por otro lado.

2022-09-20 10:50 UTC, JJ commented on README.md
> +En muchas ocasiones hemos tenido el problema de no saber qué ruta escoger ya que, dependiendo del tráfico, podría ser más rápido tomar la ruta más larga.
¿Este es un problema perosnal?

2022-09-20 10:50 UTC, JJ commented on README.md
> +Este proyecto se va a desarrollar con el fin de poder obtener la ruta más rápida a nuestro destino teniendo en cuenta el tráfico y diferentes factores. Esta información se obtendrá a partir del uso d
La lógica de negocio no puede depender nunca de servicios externos. Tendrías que ser capaz de testearla sin usarlo. Es mejor, en todo caso, que en la modelización del problema hables solamente de las características abstractas del mismo
Si usas Google, Google ya te da la ruta... Así que para ese viaje no hacen falta alforjas.

2022-09-22 06:43 UTC, pedromarting3 commented on README.md
> +En muchas ocasiones hemos tenido el problema de no saber qué ruta escoger ya que, dependiendo del tráfico, podría ser más rápido tomar la ruta más larga.
Sí

2022-09-22 06:44 UTC, pedromarting3 commented on README.md
> +Este proyecto se va a desarrollar con el fin de poder obtener la ruta más rápida a nuestro destino teniendo en cuenta el tráfico y diferentes factores. Esta información se obtendrá a partir del uso d
Perfecto, ya le he dado una vuelta. Está actualizado pendiente de su revisión @JJ

2022-09-22 09:21 UTC, JJ requested changes
Lo que me has contado en clase parecía relativamente razonable, pero en esto que has escrito no llegas al mismo nivel de detalle. Lo que se queda escrito es lo que permanece, así que te rogaría que lo detallaras en cuestión de dónde vas a obtener los datos y la lógica de negocio. También identifica claramente el cliente, si es la persona, la concejalía de urbanismo, o los dos.

2022-09-22 11:32 UTC, pedromarting3 commented
Revisado @JJ

2022-09-22 15:28 UTC, JJ approved these changes
Recuerda que los datos tienen que ser realistas cuando vayas a hacer tests. Y los diferentes usuarios que has mencionado, que tendrán sus historias de usuario.

2022-09-23 07:35 UTC, merged