[IV-22-23] Objetivo 4 de @pedromarting3
pedromarting3/OnTime pull request #26
Opened 2022-11-10 10:10 UTC by pedromarting3

2022-12-10 14:52 UTC, MauronMP commented
Revisa los nombres de los ficheros, en los errores frecuentes de la [semana 10](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-10.md) lo indica :smile:

2022-12-10 17:25 UTC, pedromarting3 commented
Muchas gracias por el vistazo @MauronMP ya lo he solucionado

2022-12-11 17:42 UTC, JJ requested changes
Creo que necesitas replantear el desarrollo de la lógica de negocio, partiendo de historias de usuario.

2022-12-11 17:42 UTC, JJ commented on Gruntfile.js
> +grunt.registerTask('test','execute test', ['exec']);
¿La indentación debajo es correcta?

2022-12-11 17:42 UTC, JJ commented on README.md
> +* [Test runner y librería de aserciones](/docs/Test.md)
Debes usar caminos relativos, no absolutos. Aquí y arriba.

2022-12-11 17:42 UTC, JJ commented on docs/Test.md
> +A la hora de escoger el test runner y la librería de aserciones que se va a utilizar se pueden escoger diferentes opciones:
Los criterios deben siempre enunciarse antes de las opciones disponibles.

2022-12-11 17:42 UTC, JJ commented on docs/Test.md
> +* Enzyme-> Su uso está realmente enfocado a react, es muy popular y está actualizado.
¿Por qué la pones entonces?

2022-12-11 17:42 UTC, JJ commented on package.json
> +    "check": "grunt check",
No tiene ningún sentido que hagas esto. Si lo haces, en realidad tu task runner es npm y no estás más que añadiendo un saco de dependencias que no necesitas.

2022-12-11 17:42 UTC, JJ commented on src/Busqueda.js
> +  diccionario = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"];
¿Seguro que no hay una forma mejor de hacer esto?

2022-12-11 17:42 UTC, JJ commented on src/Busqueda.js
> + * Clase que transforma los datos de los tramos y los utiliza para crear un arbol
O usas docstrings, o no usas nada.

2022-12-11 17:42 UTC, JJ commented on src/Busqueda.js
> +  diccionario = ["a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"];
Esto lo has añadido según #29, que 
1. No tiene nada que ver con el código
2. Un issue que es incorrecto porque lo es, y por que
3. No enlaza ninguna HU. ¿Cómo se van a hacer tests si no están relacionados con una HU?

2022-12-11 17:42 UTC, JJ commented on src/Busqueda.js
> +        if(origen && origen.trim().length != 0 && this.diccionario.includes(origen))
No sé por qué los orígenes deben estar predeterminados, y menos según un diccionario, que además no se inicializa. Dado que ese llamado "diccionario" se ha creado con un issue que no está ligado a ninguna HU, es imposible saber si está haciendo algo bien.

2022-12-11 17:43 UTC, JJ commented on test/busqueda.test.js
> +const Busqueda = require("../src/busqueda.js").Busqueda;
Los ficheros se siguen llamando igual. Esto te funciona porque estás en el Mac; petará en cualquier otro sistema.

2022-12-13 22:31 UTC, pedromarting3 commented on src/Busqueda.js
> +        if(origen && origen.trim().length != 0 && this.diccionario.includes(origen))
Efectivamente, estaba implementado de manera incorrecta.

2022-12-13 22:49 UTC, pedromarting3 commented
Ya le he echado un vistazo a lo que me dijiste y he intentado solucionarlo, cuando puedas revísamelo @JJ 🤝🤘

2022-12-14 08:36 UTC, JJ requested changes
La parte que está bien es la implementación del algoritmo (barra usas antipatrones como flags y demás), pero el resto deberías darle una vuelta. Ánimo.

2022-12-14 08:36 UTC, JJ commented on docs/Test.md
> +## Assertion libraries
Tienes *siempre* que establecer primero los criterios de búsqueda y elección, no listar las que hay y quedarte con una.

2022-12-14 08:36 UTC, JJ commented on package.json
> +    "grunt-cli": "^1.4.3",
¿Por qué son estas dependencias de producción?

2022-12-14 08:36 UTC, JJ commented on src/busquedas.js
> +        throw new Error("El origen de la ruta es imprescindible");
Por favor, consulta los errores frecuentes. La modelización del dominio incluye también modelización de las posibles excepciones. El objetivo de lanzar una excepción es la posibilidad de capturarla a otro nivel y por supuesto que desarrollador o usuario sean capaces de corregir el error. Si no das toda la información posible sobre el mismo es imposible hacerlo. En este caso, la pregunta sería "Pero ¿el destino está bien? ¿Está mal porque está indefinido o porque es una cadena que después de quitar los espacios es nula?

2022-12-14 08:36 UTC, JJ commented on src/busquedas.js
> +  let optimalPath = ['finish'];
Si vas a usar esto como "flag" (lo que es siempre una mala práctica), "finish" no va a ser un nombre de nodo válido. Tendrás que tenerlo en cuenta en el constructor.

2022-12-14 08:36 UTC, JJ commented on src/infotramos.js
> +const tramos = {
Esto no lo puedes crear a jopo en el código. O es parte del test, o lo que sea, pero no puede estar aquí.
Por otro lado, el que tengas que usar nombres específicos (como `finish`) debería estar bien establecido, y si es posible encapsulado.

2022-12-14 08:36 UTC, JJ commented on test/busqueda.test.js
> +describe("Check valid form of tramos",() => {
Los constructores se supone que funcionan correctamente. Si tienes que comprobar algo, que sea el API de la clase, no los valores. En "Arrange, act y assert", "arrange", es decir, crear el objeto, no es parte del test.

2022-12-14 08:36 UTC, JJ commented on test/busqueda.test.js
> +const Busqueda = require("../src/busquedas.js").Busqueda;
No es buena práctica cargar n veces para diferentes funciones. Usa destructuración para cargarlos todos a la vez, o carga el módulo y reasignas valores más adelante. Cada vez que cargas un módulo se interpreta, y eso retrasa todo.

2022-12-14 08:36 UTC, JJ commented on src/busquedas.js
> +function dijkstra(graph)
No es buena práctica tener detalles de implementación en el API. Los algoritmos que uses deben ser transparentes al "cliente" de tu API.

2022-12-15 08:47 UTC, JJ approved these changes
Con lo que hemos hablado (incluyendo que las funciones de un API, como la que calcula la distancia, no debe tener detalles de implementación), aprobado.

2022-12-15 11:44 UTC, merged