[IV-22-23] Objetivo 5 de @pedromarting3
pedromarting3/OnTime pull request #39
Opened 2022-12-16 08:53 UTC by pedromarting3

2023-01-02 19:18 UTC, pedromarting3 commented
@arsa-dev cuando puedas échale un vistazo 😺

2023-01-03 11:23 UTC, arsa-dev requested changes

2023-01-03 11:23 UTC, arsa-dev commented on Dockerfile
> +FROM node:latest as final
No sería necesario el `as final` ya que solamente estás trabajando con una imagen en el Dockerfile

2023-01-03 11:23 UTC, arsa-dev commented on Dockerfile
> +ENV PATH="${PATH}:${PNPM_HOME}:/home/node/.npm-global/bin"
DRY. Aquí se podría utilizar también la variable de entorno NPM_CONFIG_PREFIX añadiéndole al final /bin.

2023-01-03 11:23 UTC, arsa-dev commented on .github/workflows/image_docker.yml
> +      - 'Gruntfile.js'
Ya que solo estás copiando el package.json a la imagen que creas, no es necesario volver a generar la imagen cuando se modifica el Gruntfile. Por otro lado no es mala idea crearla cuando modificas el package-lock.json, pero deberías copiar este fichero también a la imagen de docker.

2023-01-03 12:34 UTC, pedromarting3 commented
Arreglado @arsa-dev  muchas gracias señor 😬

2023-01-03 12:41 UTC, arsa-dev approved these changes
Por lo demás lo veo todo bien 👍

2023-01-03 12:41 UTC, arsa-dev commented on .github/workflows/image_docker.yml
> +      - 'Gruntfile.js'
Aún te falta lo que te he comentado de eliminar el gruntfile.js como trigger del pipeline que genera la imagen:

> No es necesario volver a generar la imagen cuando se modifica el Gruntfile
Ya que el hecho de editar el gruntfile no va a generar una imagen distinta a la anterior

2023-01-03 12:43 UTC, pedromarting3 commented on .github/workflows/image_docker.yml
> +      - 'Gruntfile.js'
Eso es, se me había pasado quitarlo

2023-01-04 22:12 UTC, pedromarting3 commented
@JJ listo para revisión

2023-01-05 08:17 UTC, JJ requested changes
Trata de hacer una búsqueda más exhaustiva y crear el contenedor lo más simple posible.

2023-01-05 08:17 UTC, JJ commented on Dockerfile
> +RUN npm install --global pnpm grunt-cli jest
En general, todas las tareas que se tengan que hacer tienen que estar en el gestor de tareas. En este caso es una pescadilla que se muerde la cola, claro, pero lo cierto es que estás instalando aquí cosas que es posible que tengas también en el package.json, y que pueden desaparecer del mismo.
Así que en general da la impresión de que
1. Tienes cosas que no necesitas, como npm
2. No estás respetando tu propio fichero de dependencias y lo que es más importante el package-lock.json (esto va a instalar la versión que sea)
3. No estás buscando la forma de instalar, por ejemplo, `pnpm`  sin necesidad de usar npm (que se puede, no tienes más que buscarlo)
4. No estás buscando la forma más simple de usar los paquetes instalados desde el propio package.json sin necesidad de instalarlos globalmente.

2023-01-05 08:17 UTC, JJ commented on Dockerfile
> +RUN pnpm install
En este momento, ¿cuantas versiones de grunt-cli y jest vas a tener instaladas en el repositorio?

2023-01-05 08:17 UTC, JJ commented on docs/Docker-image.md
> +*Tras intentar crear nuestro propia imagen de docker, se dan problemas de compatibilidad por la arquitectura de mi ordenador por lo que voy a usar la imagen de node*
No tenían por qué. Simplemente créala en Docker Hub.

2023-01-05 08:17 UTC, JJ commented on docs/Docker-image.md
> +* Tendrán preferencia versiones oficiales.
Una cosa es que tengan preferencia y otra que no nombres otras. Ya os expliqué en clase los diferentes tipos de imágenes que había, y lo hice para que al menos las comprobárais.

2023-01-06 11:45 UTC, pedromarting3 commented on Dockerfile
> +RUN pnpm install
Cierto, no me había dado cuenta de este error

2023-01-06 11:48 UTC, pedromarting3 commented on docs/Docker-image.md
> +*Tras intentar crear nuestro propia imagen de docker, se dan problemas de compatibilidad por la arquitectura de mi ordenador por lo que voy a usar la imagen de node*
En ese momento estaba testeando todo localmente por no tener mil errores al subirlo al pr aunque finalmente lo hice en 22 intentos ;(. Una vez que aprendí que se puede crear la imagen con diferente arquitectura al local se me pasó actualizar este fichero.

2023-01-06 11:49 UTC, pedromarting3 commented on docs/Docker-image.md
> +* Tendrán preferencia versiones oficiales.
Creo que tengo casi todo en los apuntes, en un momento lo actualizo

2023-01-06 12:50 UTC, pedromarting3 commented
@jj he hecho las correcciones :)

2023-01-09 09:25 UTC, JJ requested changes
De lo comentado, el error fundamental es que hayas incluido el lockfile para `npm`. El resto tienen importancia variable, pero no bloquearían la aceptación.

2023-01-09 09:25 UTC, JJ commented on Dockerfile
> +COPY package.json /app
Una vez más, ¿por qué usas dos sentencias?

2023-01-09 09:25 UTC, JJ commented on Dockerfile
> +ENV PNPM_HOME="/.pnpm"
Igual, ¿por qué usas dos sentencias?

2023-01-09 09:25 UTC, JJ commented on Dockerfile
> +
Normalmente se pone el FROM en la primera línea. No es demasiado importante.

2023-01-09 09:25 UTC, JJ commented on Dockerfile
> +RUN wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" && chmod +x /bin/pnpm
No haría falta que lo ejecutaras como superusuario. Recuerda no hacer nada con privilegios salvo que sea estrictamente necesario.

2023-01-09 09:25 UTC, JJ commented on docs/Docker-image.md
> +* grunt image: se plantea la posibilidad de crear mi propia imagen de docker.
No has puesto en ninguna de ellas el tamaño. Si ponéis criterios objetivos, es para que toméis la decisión en base a ellos y que pongáis en las diferentes opciones consideradas de qué forma cumplen, o no, los criterios.

2023-01-09 09:25 UTC, JJ commented on package-lock.json
>      "": {
¿Para qué quieres esto en el repo, si usas pnpm?

2023-01-09 10:31 UTC, pedromarting3 commented on Dockerfile
> +RUN wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" && chmod +x /bin/pnpm
Si ponía la sentencia "USER node" encima del wget me daba error de permisos, por eso lo puse así. Probé varias alternativas pero sin solucionarlo 😮‍💨

2023-01-09 10:37 UTC, JJ commented on Dockerfile
> +RUN wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" && chmod +x /bin/pnpm
No shit. Uno de los objetivos de este, ejem, objetivo era que refrescárais vuestro conocimiento de la línea de órdenes de Linux. Deberías haber intentado, como cualquier error, saber
1. Qué comando es el que está produciendo el error
2. A qué se debe, leyendo atentamente la información proporcionada por el mensaje de error.
3. Cómo solucionarlo creando un issue, que para eso son los issues, para problemas.

2023-01-09 11:11 UTC, pedromarting3 commented on Dockerfile
> +RUN wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" && chmod +x /bin/pnpm
He abierto el issue #41 en el que he expuesto el problema y la solución adoptada

2023-01-09 11:20 UTC, pedromarting3 commented
@JJ ya he revisado las correcciones que me ha propuesto 🏌🏽‍♂️

2023-01-10 06:52 UTC, JJ requested changes
Me temo que te has alejado del objetivo. Has dejado de hacer cosas que eran válidas, y simplemente has maquillado una descarga con privilegios de superusuario dentro de una sentencia que, además, has escrito contra las buenas prácticas en una sola línea.
Te agradecería que para optimizar el tiempo de todos, no solicitaras revisión a menos que soluciones adecuadamente los problemas indicados.

2023-01-10 06:52 UTC, JJ commented on .github/workflows/image_docker.yml
> +      - 'package-lock.json'
Pero ¿usas `npm` o `pnpm`?

2023-01-10 06:52 UTC, JJ commented on Dockerfile
> +COPY package.json /app
Y ahora, ¿por qué ya no copias uno de los ficheros? Os expliqué en clase varias veces para qué servían los lockfile.

2023-01-10 06:52 UTC, JJ commented on Dockerfile
> +RUN chown -R node /app && wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" && chmod +x /bin/pnpm
También es buena práctica dividir esto en varias líneas, y deberías saber como. Las sentencias largas nunca son buenas porque provocan scrolling horizontal en el editor. Por otro lado, lo estás ejecutando con los mismos permisos que antes.

2023-01-10 06:52 UTC, JJ commented on docs/Docker-image.md
> +* node: podría usarla por su estabilidad, versatilidad y compatibilidad con mi proyecto.
Podías intentar poner enlaces.

2023-01-12 08:39 UTC, pedromarting3 commented on .github/workflows/image_docker.yml
> +      - 'package-lock.json'
En [este archivo](https://github.com/pedromarting3/OnTime/blob/objetivo3/docs/gestor_dependencias.md) decidí que iba a usar npm por lo que voy a modificar todo para usar el mismo

2023-01-12 09:28 UTC, pedromarting3 commented on .github/workflows/image_docker.yml
> +      - 'package-lock.json'
Cuando escogí el gestor de dependencias decidí usar npm por lo que voy a usarlo

2023-01-12 09:52 UTC, pedromarting3 commented
@JJ creo que he solucionado todo lo que me ha propuesto, me he querido esperar a solicitar la revisión después de la tutoría que impartió el otro dia. He abierto nuevos issues que se han ido planteando cuando estaba modificando el dockerfile. Como le he puesto arriba, usaré npm ya que es lo que se decidió en su momento -> [aquí](https://github.com/pedromarting3/OnTime/blob/objetivo3/docs/gestor_dependencias.md).  
Está listo para revisión ✌🏽

2023-01-12 10:17 UTC, JJ requested changes
Sigues sin seguir las buenas prácticas en la construcción del contenedor, como no dejar ficheros en la misma que no sean necesarios. Por otro lado, has optado por la opción más simple posible del contenedor base sin tratar de investigar otras opciones y sin seguir las buenas prácticas en el mismo, que es precisamente de lo que se trata el objetivo.

2023-01-12 10:17 UTC, JJ commented on .github/workflows/image_docker.yml
> +      - 'package-lock.json'
Entonces, ¿cómo diablos acabó aquí `pnpm`?

2023-01-12 10:17 UTC, JJ commented on .github/workflows/image_docker.yml
> +        uses: docker/login-action@v1
Conviene siempre que uséis la última versión disponible. ¿Has comprobado si esta lo es?

2023-01-12 10:17 UTC, JJ commented on Dockerfile
> +#Ejecuciones con root
Os he dicho repetidamente que no uséis comentarios en línea.

2023-01-12 10:17 UTC, JJ commented on docs/Docker-image.md
> +* [node](https://hub.docker.com/_/node): podría usarla por su estabilidad, versatilidad y compatibilidad con mi proyecto.
"podría usarla" no describe cómo se adapta la imagen (o no) a los criterios que has puesto arriba.

2023-01-12 10:17 UTC, JJ commented on docs/Docker-image.md
> +* Tendrán preferencia versiones oficiales.
No hay ninguna razón por la que se tengan que preferir versiones oficiales. Si la hay, pon los criterios por los que se prefieren.

2023-01-12 10:17 UTC, JJ commented on docs/Docker-image.md
> +* Versión: se usará la versión más estable para que nuestro proyecto tenga el mejor soporte a pesar de perder ciertas funcionalidades que se hayan añadido en versiones nuevas (menos estables).
Este es un contenedor para test. Puedes escoger estabilidad, o lo contrario. En cualquier caso, no parece un criterio objetivo, es simplemente uno subjetivo.

2023-01-12 10:17 UTC, JJ commented on docs/Docker-image.md
> +* [buster-slim](https://hub.docker.com/r/linuxcontainers/buster-slim): contenedor basado en debian que, como su nombre lo indica es liviana (64.03MB). No la voy a usar porque no se ajusta a las neces
No es comparable con la anterior, simplemente porque no contiene node. No puedes comparar el tamaño de las mismas.

2023-01-12 10:17 UTC, JJ commented on docs/Docker-image.md
> +Otra opción que he encontrado y me parece interesante es:
¿Sólo esa? ¿No hay otras versiones bases con Linux? ¿Otras versiones que empaqueten node?

2023-01-12 10:17 UTC, JJ commented on docs/Docker-image.md
> +Finalmente he decidido hacer uso de la imagen oficial de node en su última versión ya que, a pesar de ser la más pesada se trata de un proyecto en los que los diferentes elementos que lo componen se
La "pesadez" es la única razón por la que *no* deberíais elegir una imagen. Tampoco puedes comparar imágenes con node con imágenes que no lo tienen.

2023-01-24 12:00 UTC, pedromarting3 commented
He estado pensando sobre la imagen que seleccioné en su momento  y actualmente no pienso que sea apropiada. Realizo las modificaciones necesarias para usar otra imagen.

2023-01-25 14:07 UTC, pedromarting3 commented
@JJ listo para revisión

2023-01-25 16:30 UTC, JJ requested changes
Hay varios problemas tanto en el Dockerfile como en la elección de la base, pero el principal problema es que no estoy seguro de que funcione.

2023-01-25 16:30 UTC, JJ commented on .github/workflows/image_docker.yml
> +      - 'package-lock.json'
:eye: mira todos los comentarios.

2023-01-25 16:30 UTC, JJ commented on .github/workflows/image_docker.yml
> +        uses: docker/login-action@v1
:eyes: también estos.

2023-01-25 16:30 UTC, JJ commented on docs/Docker-image.md
> +* [huli/grunt](https://hub.docker.com/r/huli/grunt/#!): Esta imagen se ha creado con el objetivo de ejecutar tareas de grunt en alpine, su tamaño es de 350MB (aproximadamente) Un punto a tener en cue
¿Sabes que puedes actualizar todo el contenido de la imagen si te apetece? ¿O, como os dije en clase, mirar cómo está hecha y modificarla para tus propósitos?

2023-01-25 16:30 UTC, JJ commented on docs/Docker-image.md
> +* [vmware/node](https://hub.docker.com/r/vmware/node): contenedor basado en Photon Os, una distribución minimalista de Linux que está optimizada para su funcionamiento en contenedores. Su tamaño apro
¿Y qué más necesitas? En todo caso, no puedes descartarla por criterios que no hayas enunciado previamente.

2023-01-25 16:30 UTC, JJ commented on docs/Docker-image.md
> +* [buster-slim](https://hub.docker.com/r/linuxcontainers/buster-slim): contenedor basado en debian que, como su nombre indica es liviana (64.03MB). Hay que tener en cuenta que una de las razones por
No puedes comparar imágenes con node con imágenes que no lo tienen. La forma correcta de hacerlo sería tomar la imagen sin node, instalarlo, y entonces comparar.

2023-01-25 16:30 UTC, JJ commented on Dockerfile
> +RUN npm ci
¿En qué directorio se está ejecutando esto? ¿Qué hace exactamente y donde? ¿Has probado que funciona?

2023-01-25 16:30 UTC, JJ commented on Dockerfile
> +
¿Seguro que se tienen que quedar en la imagen los ficheros que has copiado?

2023-01-25 16:30 UTC, JJ commented on Dockerfile
> +ENTRYPOINT [ "grunt", "test" ]
¿Seguro que funciona? ¿Lo has probado?

2023-01-26 09:42 UTC, pedromarting3 commented on .github/workflows/image_docker.yml
> +      - 'package-lock.json'
Hubo un momento en el que pensé en cambiarlo, pero finalmente he decidido que no

2023-01-26 10:13 UTC, pedromarting3 commented
@JJ ya he corregido lo que me ha dicho👍🏻

2023-01-26 11:38 UTC, JJ requested changes
Es posible que funcione, pero aún así no estás siguiendo buenas prácticas porque sigues sin tener muy claro dónde se ejecuta cada cosa y qué es lo que hace. Te aconsejaría que entraras en el contenedor y vieras dónde está cada cosa y en función de eso tomaras unas cuantas decisiones.

2023-01-26 11:38 UTC, JJ commented on docs/Docker-image.md
> +* [buster-slim](https://hub.docker.com/r/linuxcontainers/buster-slim): contenedor basado en debian que, como su nombre indica es liviana (64.03MB). Hay que tener en cuenta que una de las razones por
Una vez más, estás mezclando versiones con node con versiones sin node. Los tamaños publicados en Docker Hub son comprimidos; 800 megas es posible que se queden en muchos menos, o en todo caso tendrás que compararlo con las versiones descargadas del resto.

2023-01-26 11:38 UTC, JJ commented on package.json
> +    "grunt-contrib-uglify": "^5.2.2",
¿Esto dónde lo usas?

2023-01-26 11:38 UTC, JJ commented on Dockerfile
> +RUN npm install -g grunt-cli jest && npm ci && rm /app/package-lock.json /app/package.json
`grunt-cli` y `jest` lo estás instalando dos veces. Tiene sentido que lo hagas para `grunt-cli`, pero no para `jest`. Si no te lo encuentra, tendrás que ejecutarlo (desde `grunt`) de forma que lo encuentre. ¿Qué comando se usa para ejecutar comandos instalados por `npm` *como si se estuvieran ejecutando desde npm*?

2023-01-26 11:38 UTC, JJ commented on Dockerfile
> +ENV NPM_CONFIG_PREFIX="/home/node/.npm-global"
¿Esto hace falta para qué?

2023-01-26 11:38 UTC, JJ commented on Dockerfile
> +RUN npm install -g grunt-cli jest && npm ci && rm /app/package-lock.json /app/package.json
Por otro lado, te vuelvo a repetir lo mismo que antes. ¿Dónde está ejecutándose esto? ¿Sobre qué ficheros se está ejecutando? ¿Qué está generando y en qué directorio?

2023-01-26 11:38 UTC, JJ commented on Dockerfile
> +ENTRYPOINT [ "grunt", "test" ]
Y te vuelvo a repetir lo mismo. Es muy posible que funcione, pero por razones diferentes a las que tú crees que funciona. Para ver si *realmente* funciona, probaría a incluir otra biblioteca que no sea ni jest ni grunt y usarla para test.

2023-01-27 08:51 UTC, pedromarting3 commented on docs/Docker-image.md
> +* [buster-slim](https://hub.docker.com/r/linuxcontainers/buster-slim): contenedor basado en debian que, como su nombre indica es liviana (64.03MB). Hay que tener en cuenta que una de las razones por
Lo de los tamaños del docker hub no les hago caso, todos los tamaños que están puestos aquí han sido después de hacer el pull desde docker hub (en el caso de buster slim, haciendo el pull y descargando lo que necesitaba para que estuviese en condiciones parecidas al resto)

2023-01-27 12:12 UTC, pedromarting3 commented
@JJ Listo para revisión 👌🏼

2023-01-27 12:20 UTC, JJ requested changes
Bastante cerca. Pero todavía un paso...

2023-01-27 12:20 UTC, JJ commented on Dockerfile
> +RUN npm install -g grunt-cli
¿Con qué privilegios estás instalando esto?

2023-01-27 12:20 UTC, JJ commented on package.json
> +    "url-parse": "^1.5.10"
Esto lo puedes quitar ya.

2023-01-27 12:33 UTC, pedromarting3 commented on Dockerfile
> +RUN npm install -g grunt-cli
Con root, porque lo estoy descargando global

2023-01-27 12:36 UTC, pedrooot commented
@JJ listo de nuevo

2023-01-27 16:14 UTC, JJ approved these changes
:+1:

2023-01-27 16:14 UTC, JJ commented on Dockerfile
> +WORKDIR /app
Esto lo podías pasar a la línea 10. Es conveniente en los Dockerfile (y en general, en cualquier aplicación) emitir un comando lo más cerca posible de donde efectivamente lo uses.

2023-01-27 16:14 UTC, JJ commented on Gruntfile.js
> +      jest: 'npx jest test/*.js'
Es muy probable que puedas usar `jest` solo. ¿Lo has probado?

2023-01-27 17:20 UTC, merged