[IV-22-23] Objetivo 2 de @JaimeGM96 en repositorio de @pedromarting3
pedromarting3/OnTime pull request #8
Opened 2022-10-07 10:49 UTC by JaimeGM96

En este PR se va a realizar la primera implementación de código en este repositorio avanzando así en la [HU2](https://github.com/pedromarting3/OnTime/issues/6) y en el [M1](https://github.com/pedromarting3/OnTime/milestone/1).

El primer paso es la elección del lenguaje de programación. Para ello se ha creado un nuevo issue #7 donde se decidirá cuál es lenguaje que se ha elegido.

# Lista de comprobación
## Sobre la estructura del repositorio
* [ ] ¿He seguido las mejores prácticas en nombre de las clases y ficheros y disposición de los mismos?
## Sobre el análisis del problema
* [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo que se ha creado?
* [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor, una entidad o un agregado?
* [ ] ¿He propuesto un producto mínimamente viable, que en general será un solo objeto valor que no dependa de ningún otro (y que sea la base de muchos otros)?.
## Sobre la planificación y la programación
* [ ] ¿Los issues representan un problema, y no una tarea?
* [ ] ¿Todos los mensajes de commit explican el cambio, y no se limitan a repetir el nombre del fichero que se ha cambiado?
* [ ] ¿Los mensajes de commit siguen el [el formato estándar y las buenas prácticas](https://www.theserverside.com/video/Follow-these-git-commit-message-guidelines).
* [ ] ¿Se ha hecho una revisión real del código para comprobar que todos los atributos y funciones creadas están respaldadas por una HU?
* [ ] ¿Todos los issues creados están asignados a una HU?
* [ ] ¿Todos los cambios en el código están asignados a un issue?
* [ ] Los issues sobre los que estoy trabajando, ¿han sido asignados al primer milestone?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [ ] ¿Son los milestones sobre los que estoy trabajando productos mínimamente viables? ¿O tengo que solicitar al product manager que cree milestones adicionales o precise de qué producto se trata?

2022-10-15 16:55 UTC, JaimeGM96 commented
He subido los ficheros de las clases que hemos estado comentando en el issue #9. He añadido algún atributo más a algunas de las clases. Coméntame lo que consideres que haya que modificar y sigo trabajando en ellas.

2022-10-15 17:08 UTC, JaimeGM96 commented
¿Podrías asignar el milestone 0 a este pull request, @pedromarting3?

2022-10-15 17:47 UTC, pedromarting3 commented
Buenas @JaimeGM96 estoy fuera de casa y desde el movil no puedo hacerlo, mañana a primera hora te digo algo.  

Muchas gracias por tu trabajo 😝😝

2022-10-15 17:54 UTC, JaimeGM96 commented
Perfecto 👍🏼

2022-10-16 08:48 UTC, pedromarting3 commented
Buenas @JaimeGM96 le he hechado un vistazo a todo y la vd es que me parece casi todo correcto. El único pero que le encuentro es que podríamos identificar al usuario a través de su correo electrónico electrónico en vez de por su id (tendría similitud con lo hecho en los coches, que se identifican con su matrícula y no es necesario que tengan ID). En el caso de que quieras mantener el ID de los usuarios, también habría que tener un ID para los coches por mantener la regularidad del código.  

Por lo demás lo veo todo bastante bien Jaime, si no te importa me espero a aprobarte el pull a esta noche o mañana por la mañana por si se nos ocurre algo mas.  

Ya casi está, muchas gracias por todo boss 🫡

2022-10-16 09:26 UTC, JaimeGM96 commented
Hola @pedromarting3, me parece bien el cambio, me pongo ahora mismo a arreglarlo 🫡.

2022-10-17 10:58 UTC, pedromarting3 approved these changes
Apruebo! @JaimeGM96

2022-10-20 05:21 UTC, JJ requested changes
Ningún intento por modelizar el problema. Sólo se toman los "objetos" identificados en el problema y se hace una estructura de datos para ellos que nada tiene que ver con el problema en si ni con ninguna historia de usuario. Lo siento, pero la metodología explicada tiene que aplicarse, para eso está.

2022-10-20 05:21 UTC, JJ commented on src/Tramo.js
> +     * @param {Number} id Identificador del tramo
¿Por qué hay un identificador?

2022-10-20 05:21 UTC, JJ commented on src/Ruta.js
> +class Ruta {
¿Qué hace exactamente esta clase?

2022-10-20 05:21 UTC, JJ commented on src/Usuario.js
> +     * @param {String} email Email del usuario
¿Qué historia de usuario pide el email del usuario? O, para el caso, un usuario.

2022-10-26 07:53 UTC, JaimeGM96 commented on src/Ruta.js
> +class Ruta {
La clase Ruta es la que almacena los tramos que recorre un Usuario. Por ejemplo, si vas desde Armilla a La Zubia, esa ruta, realizada por un Usuario determinado, tendrá una serie de Tramos. Uno de ellos puede ser desde el punto de inicio de Armilla hasta la salida que nos asegure llegar en el menor tiempo posible. La salida del centro comercial Nevada un día de fin de semana puede no ser la mejor opción a coger.

2022-10-26 07:57 UTC, JaimeGM96 commented on src/Tramo.js
> +     * @param {Number} id Identificador del tramo
Para saber cuál es el Tramo que estamos viendo. Se podría añadir un atributo de hora para diferenciar entre los Tramos que tienen los mismos puntos de origen y destino pero que en determinados momentos del día son más o menos adecuados según el tráfico.

2022-10-26 07:59 UTC, JJ requested changes
Por favor, mirad los errores frecuentes en la sesión de esta semana (y la anterior) y realizad este objetivo según la metodología y las mejores prácticas indicadas.

2022-10-26 07:59 UTC, JJ commented on src/Ruta.js
> + * Declaración de la clase Ruta
¿Es necesario esto?

2022-10-26 07:59 UTC, JJ commented on src/Ruta.js
> +class Ruta {
¿Y en qué parte de #9 dice eso? ¿Dónde está el "número de paradas" que *sí* dice?
(no te estoy diciendo que lo pongas, sino que tienes que plantear los *problemas* que tienes que solucionar con este modelo y solucionarlo en el PR)

2022-10-26 07:59 UTC, JJ commented on src/Ruta.js
> +     * @param {String} emailUsuario Identificador del usuario mediante su email
> La clase Ruta es la que almacena los tramos que recorre un Usuario. Por ejemplo, si vas desde Armilla a La Zubia, esa ruta, realizada por un Usuario determinado, tendrá una serie de Tramos. Uno de ellos puede ser desde el punto de inicio de Armilla hasta la salida que nos asegure llegar en el menor tiempo posible. La salida del centro comercial Nevada un día de fin de semana puede no ser la mejor opción a coger.

Y por eso necesita el email del usuario, ¿no?

2022-10-26 08:02 UTC, JJ commented on src/Tramo.js
> +     * @param {Number} id Identificador del tramo
> Para saber cuál es el Tramo que estamos viendo. Se podría añadir un atributo de hora para diferenciar entre los Tramos que tienen los mismos puntos de origen y destino pero que en determinados momentos del día son más o menos adecuados según el tráfico.

¿No se identifica el tramo por el origen y destino? ¿Cómo accede a él la lógica de negocio? 

Por otro lado, se podría añadir sólo lo que resuelva el problema que se debería de haber planteado en un issue. Cualquier otra cosa es exponer tu código a la arbitrariedad de quien lo revisa y crear deuda técnica para quien vaya trabajando en él más adelante. Y por supuesto sólo lo mínimo que exija el PMV correspondiente.

2022-10-26 08:18 UTC, JJ commented
> Ningún intento por modelizar el problema. Sólo se toman los "objetos" identificados en el problema y se hace una estructura de datos para ellos que nada tiene que ver con el problema en si ni con ninguna historia de usuario. Lo siento, pero la metodología explicada tiene que aplicarse, para eso está.

Y esto te lo dije hace 6 días. Es cierto que podéis entregar los objetivos cuando queráis, pero lo cierto es que hay un tiempo limitado para entregar un número concreto de objetivos.

2022-10-26 08:30 UTC, JaimeGM96 commented
> > Ningún intento por modelizar el problema. Sólo se toman los "objetos" identificados en el problema y se hace una estructura de datos para ellos que nada tiene que ver con el problema en si ni con ninguna historia de usuario. Lo siento, pero la metodología explicada tiene que aplicarse, para eso está.
> 
> Y esto te lo dije hace 6 días. Es cierto que podéis entregar los objetivos cuando queráis, pero lo cierto es que hay un tiempo limitado para entregar un número concreto de objetivos.

Lo sé, me ha sido imposible hacerlo antes, intentaré contestar mucho más rápido.

2022-10-27 09:02 UTC, JaimeGM96 commented
He realizado los cambios que hemos comentado en los issues

2022-10-27 10:05 UTC, pedrooot commented on src/Tramo.js
> +        this.matriculaVehiculo = matriculaVehiculo;
Buenas @JaimeGM96 pienso que el atributo matriculaVehiculo no es necesario. Me explico: 
El tramo forma parte de una ruta, y una ruta es recorrida por x vehículo. No veo necesario que un tramo tenga asignada un vehículo porque en este caso el es el objeto valor y es inmutable. A lo que me refiero es que el vehículo puede tener asociada una ruta con un conjunto de tramos, no al contrario.

2022-10-27 10:05 UTC, pedrooot commented on src/TipoVehiculo.js
> +import Enum from 'enum';
Si quieres hacer un enum no hace falta que lo importes.

2022-10-27 10:05 UTC, pedromarting3 commented on src/TipoVehiculo.js
> +const tipoVehiculo = new Enum({
Sería mejor usar un diccionario en vez de un enumerado. De todas formas no estás usando esta clase en ninguna parte y quizás te va a traer mas problemas que ventajas. En este objetivo no es necesario implementar validaciones así que yo eliminaría esta clase.

2022-10-27 10:06 UTC, pedromarting3 commented
Esto tiene buena pinta @JaimeGM96 intenta corregir lo que te he puesto y te apruebo.😬

2022-10-27 10:58 UTC, JaimeGM96 commented on src/Tramo.js
> +        this.matriculaVehiculo = matriculaVehiculo;
¿Entonces ves mejor que el vehículo esté en la ruta completa en vez de en cada Tramo?

2022-10-27 11:03 UTC, JaimeGM96 commented on src/TipoVehiculo.js
> +const tipoVehiculo = new Enum({
Lo estaba usando en la clase Vehículo pero lo quito sin problema 👍🏼. No estoy muy familiarizado con los Enums en js, si crees que un diccionario es mejor opción lo cambiamos por eso, o si prefieres que lo quite del todo lo quito.

2022-10-27 11:10 UTC, pedromarting3 commented on src/TipoVehiculo.js
> +const tipoVehiculo = new Enum({
Creo que es mejor quitarlo

2022-10-27 11:14 UTC, pedromarting3 commented on src/Tramo.js
> +        this.matriculaVehiculo = matriculaVehiculo;
Así es, yo tomaría como que "x" vehículo pasa por "y" ruta. Si asignamos los vehículos a las rutas (rutas tienen vehículos) no tiene mucha lógica, es mejor que el vehículo tenga la ruta (vehículo tiene ruta)

2022-10-27 12:52 UTC, JaimeGM96 commented
Ya está modificado lo último que hemos comentado 👍🏼

2022-10-27 15:28 UTC, JJ requested changes
Por favor, tratad de seguir la metodología propuesta en clase.

2022-10-27 15:28 UTC, JJ commented on src/Ruta.js
> +class Ruta {
No se ha hecho ninguna modificación con respecto a los comentarios hechos anteriormente. Se ha cambiado, y mal, el contenido de los issues.

2022-10-28 09:52 UTC, JaimeGM96 commented
He creado un issue donde se plantea el problema que tenemos y se mencionan los issues de las creaciones de las clases donde se definen las posibles estructuras de datos que resuelvan el problema.

2022-10-28 10:15 UTC, JJ reviewed
Por favor, no solicitéis revisión hasta que no reviséis todo lo que se os haya comentado. He indicado dos objeciones señaladas con :arrow_up:, pero hay algunas más.

2022-10-28 10:15 UTC, JJ commented on src/Ruta.js
> + * Declaración de la clase Ruta
:arrow_up:

2022-10-28 10:15 UTC, JJ commented on src/Ruta.js
> +class Ruta {
:arrow_up:

2022-10-28 10:54 UTC, pedromarting3 commented on src/Tramo.js
> +     * @param {Number} id Identificador del tramo
Decidimos que el tramo tuviese un "id" porque dos tramos pueden tener un mismo origen y un mismo destino por lo que no podrían ser distinguibles por estos atributos.

2022-10-28 11:06 UTC, pedromarting3 commented
@JaimeGM96 actualiza los issues, muchos de ellos tienen texto repetido en la descripción y nos está llevando a equivocaciones. Intenta mirar también el #10 y #9 porque ha faltado añadir el atributo número de paradas. En cuanto soluciones esto acepto 😬

2022-10-28 11:06 UTC, JJ commented on src/Tramo.js
> +     * @param {Number} id Identificador del tramo
¿En qué parte de la lógica de negocio dice eso? Si la lógica de negocio necesita distinguir entre dos tramps y puede que haya alguna otra cosa que lo distinga, ¿será que hace falta alguna otra cosa más para distinguir los dos tramos? ¿Cómo va a elegir la lógica de negocio entre uno y otro, si sólo se diferencian en el ID?
Insisto, el "product manager" no tiene que "decidir" nada. Tiene que aclarar cómo se usa algo en la lógica de negocio para que el desarrollador proponga una solución.
Te recuerdo además la presentación sobre DDD: los objetos-valor son indistinguibles. Si quieres que se distingan, tienes que añadir algún atributo que los distinga. No puedes distinguirlos por el ID.

2022-10-28 11:12 UTC, JaimeGM96 commented on src/Tramo.js
> +     * @param {Number} id Identificador del tramo
Los tramos que tengan el mismo origen y destino se pueden diferenciar por el tiempo medio que se tarda en recorrer teniendo en cuenta la hora de inicio del tramo.

2022-10-28 11:15 UTC, pedromarting3 commented on src/Tramo.js
> +     * @param {Number} id Identificador del tramo
Así es, ¿piensas que sea necesario el id del tramo?

2022-10-28 11:15 UTC, JJ commented on src/Tramo.js
> +     * @param {Number} id Identificador del tramo
No me lo cuentes. O lo escribes y @pedromarting3 comprueba si es un modelo aceptable del problema y compatible con la lógica de negocio o, lo correcto, pides aclaración sobre qué es lo que va a hacer la lógica de negocio en el issue correspondiente.

2022-10-28 11:15 UTC, pedromarting3 commented on src/Tramo.js
> +     * @param {Number} id Identificador del tramo
Yo creo que no

2022-10-28 11:20 UTC, JaimeGM96 commented
He puesto al final de los issues la estructura de las clases que llevamos pensada hasta el momento.

2022-10-28 11:25 UTC, pedromarting3 approved these changes
👍🏻 Gracias por tu trabajo @JaimeGM96

2022-10-30 12:20 UTC, JaimeGM96 commented
Resuelto el conflicto con la rama main 👍🏼

2022-11-02 08:48 UTC, JaimeGM96 commented
Solicito revisión @JJ

2022-11-02 09:09 UTC, JJ requested changes
Por favor, revisa el concepto de domain driven design y úsalo en el análisis del problema.
Por otro lado, te rogaría que miraras las buenas prácticas en mensajes de commit y que las pusieras en práctica.

2022-11-02 09:09 UTC, JJ commented on src/Usuario.js
> +     * @param {String} email Email del usuario
:arrow_up:

2022-11-02 09:09 UTC, JJ commented on src/Usuario.js
> +     * @param {Array[Map]} infoRutas Informacion de las Rutas realizadas por el usuario
¿Dónde dice aquí que la información en inforutas es la que has "propuesto" en #23? No se trata de que propongáis cosas, se trata de que analicéis y escribáis código. Este cambio que has hecho en realidad, dado que no aporta información adicional, no sirve de nada. Funcionalmente es un cambio de nombre, lo único que has cambiado es la documentación (y eso también es incorrecto)

2022-11-02 21:26 UTC, JaimeGM96 commented
Realizados los cambios según la información proporcionada tanto en el milestone 0 como en las historias de usuario. Se ha modelizado el problema creando tanto entidades como objetos valor.

2022-11-03 06:05 UTC, JJ commented
Por favor, seguid las buenas prácticas en los mensajes de commit: 50 + 80 con referencia al issue en la primera línea

2022-11-03 06:22 UTC, JJ requested changes
Creo que deberíais investigar mejor el concepto de entidad y objeto valor, y también domain driven design, que va un poco más allá de asignar etiquetas a clases.

2022-11-03 06:22 UTC, JJ commented on src/Ruta.js
> + * Declaración de la clase Ruta. Entidad. Esta clase representa una ruta, que está formada por un conjunto de tramos
Este commit no ha añadido ningún objeto valor, simplemente ha cambiado el comentario. Conviene que los mensajes de commit sean también veraces.

2022-11-03 06:22 UTC, JJ commented on src/Usuario.js
> +     * @param {Array[InfoRuta]} infoRutas Informacion de las Rutas realizadas por el usuario
¿Rutas realizadas por el usuario?

2022-11-03 06:22 UTC, JJ commented on src/InfoRuta.js
> +     * @param {Number} tiempoMedio Tiempo medio de la ruta que se ha realizado
¿JS no tiene ningún tipo para representar duración temporal?

2022-11-03 06:22 UTC, JJ commented on src/InfoRuta.js
> +    constructor(nombre, tiempoMedio, horaInicio) {
¿Del nombre se tiene que deducir dónde empieza y dónde acaba la ruta?

2022-11-03 06:22 UTC, JJ commented on src/Tramo.js
> +     * @param {Number} tiempoMedio Tiempo medio del tramo
Media, ¿sobre qué?

2022-11-03 06:22 UTC, JJ commented on src/Tramo.js
> +     * @param {Number} horaInicio Hora de inicio del tramo
??? ¿Y qué es una infoRuta entonces?

2022-11-03 06:22 UTC, JJ commented on src/Ruta.js
> +        this.tramos = tramos;
¿Una ruta tiene tramos cuya hora de inicio no cambia?

2022-11-03 06:22 UTC, JJ commented on src/Ruta.js
> +        this.tramos = tramos;
¿Una ruta tiene tramos cuya hora de inicio no cambia?

2022-11-03 06:22 UTC, JJ commented on src/Tramo.js
> + * Declaración de la clase Tramo. Entidad. Esta clase representa un tramo de una ruta, que está compuesto por un punto de origen,
¿Te parece que esta frase aporta algo?

2022-11-03 06:22 UTC, JJ commented on src/InfoRuta.js
> + * Clase InfoRuta. Objeto valor. En esta clase almacenaremos la información perteneciente a una ruta que ha realizado.
¿Por qué es esto un objeto valor?

2022-11-03 06:22 UTC, JJ commented on src/InfoRuta.js
> + * Clase InfoRuta. Objeto valor. En esta clase almacenaremos la información perteneciente a una ruta que ha realizado.
¿Por qué es esto un objeto valor?

2022-11-03 12:46 UTC, JaimeGM96 commented
La clase Vehiculo y los datos que contenía no se van a tener en cuenta en esta fase del desarrollo.

En cuanto al Tramo, se ha definido los atributos que va a tener. Un Tramo que tiene el mismo origen y destino o, si hay un Tramo que tenga el mismo origen que el destino de otro y viceversa, ambos son el mismo Tramo.

2022-11-03 13:06 UTC, JaimeGM96 commented
Las clases Usuario, InfoRuta y Ruta se han eliminado. Voy a empezar desde el principio únicamente con la clase Tramo que se ha planteado arriba.

2022-11-04 09:04 UTC, pedromarting3 commented
Buenas @JaimeGM96 pienso que esto se está extendiendo demasiado y me está parando un poco. Te propongo que ajustes el objetivo 2 a la implementación de la case tramo.

2022-11-04 09:07 UTC, pedromarting3 commented
La implementación que has hecho hasta hora la veo correcta, simplemente podrías añadir el atributo distancia para poder calcular el tiempo que se va a tardar en recorrer el tramo. El resto está bastante bien, intenta añadir eso y apruebo 👍🏻

2022-11-04 14:46 UTC, JaimeGM96 commented
Ya está implementada la distancia entre los puntos origen y destino. Con eso quedaría lista la clase Tramo.

2022-11-06 11:06 UTC, pedromarting3 approved these changes
Perfecto!👍🏻

2022-11-07 14:37 UTC, JJ approved these changes
No parece que el ámbito de este PR sea demasiado amplio, pero supongo que a estas horas lo que interesa es superarlo. :+1:

2022-11-08 11:25 UTC, merged